/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package interfaz;

import Prueba.Prueba3;
import java.awt.Component;
import java.awt.Container;
import java.awt.event.ActionListener;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;

/**
 *
 * @author PC
 */
public class FiltroTexto extends javax.swing.JPanel {

    /**
     * Creates new form FiltroTexto
     */
    public FiltroTexto() {

        initComponents();
        //actualizarTablaDatos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jTextField2 = new javax.swing.JTextField();
        botonBuscar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaFiltro = new javax.swing.JTable();
        botonExamen = new javax.swing.JButton();

        jTextField1.setText("jTextField1");

        jPanel1.setBackground(new java.awt.Color(253, 207, 216));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Filtro");

        jPanel2.setBackground(new java.awt.Color(250, 132, 155));

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        botonBuscar.setText("Buscar");
        botonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonBuscar)
                .addGap(62, 62, 62))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonBuscar))
                .addGap(9, 9, 9))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        tablaFiltro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Contenido", ""
            }
        ));
        tablaFiltro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaFiltroMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaFiltro);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        botonExamen.setText("Prueba");
        botonExamen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonExamenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(botonExamen))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(botonExamen))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    /*public void actualizarTablaDatos() {
        String[][] estructura de grupos = lectura de datos();
        DefaultTableModel model = (DefaultTableModel) tablaFiltro.getModel();
        model.setRowCount(0);

        for (String[] leer : datos) {
            Object[] rowData = {contenido de pregunta, "Comenzar"};
            model.addRow(rowData);
        }
    }*/
        
     // Configuracion para que la tabla de proyectos no sea editable y desactiva la reorganización de columnas.

/*
    public void actualizarTablaDatos() {
        String[][] datosProyectos = gestorFiltro.obtenerDatosProyectos();
        DefaultTableModel model = (DefaultTableModel) tablaFiltro.getModel();
        model.setRowCount(0);

        for (String[] datosProyecto : datosProyectos) {
            Object[] rowData = {datosProyecto[0]; "Empesar"};
            model.addRow(rowData);
        }
    }
        */
     // Configuracion para que la tabla de proyectos no sea editable y desactiva la reorganización de columnas.


    public void actualizarTablaDatos() {
            String obtenerFiltro = Prueba3.obtenerFiltro();
            DefaultTableModel model = (DefaultTableModel) tablaFiltro.getModel();
            model.setRowCount(0);

            Object[] rowData = {obtenerFiltro, "Ingresar"};
            model.addRow(rowData);

            // Ajusta automáticamente la altura de las filas según el contenido
            ajustarAlturaFilas();
        }


    private void ajustarAlturaFilas() {
        for (int row = 0; row < tablaFiltro.getRowCount(); row++) {
            int rowHeight = tablaFiltro.getRowHeight();

            Component comp = tablaFiltro.prepareRenderer(tablaFiltro.getCellRenderer(row, 0), row, 0);
            rowHeight = Math.max(rowHeight, comp.getPreferredSize().height);

            tablaFiltro.setRowHeight(row, rowHeight);
        }
    }


private void configurarTabla() {
        tablaFiltro.setDefaultEditor(Object.class, null); // Hace que todas las celdas no sean editables

        // Desactiva la reorganización de columnas
        tablaFiltro.getTableHeader().setReorderingAllowed(false);

        // Configura el renderizador de celdas para permitir saltos de línea
        DefaultTableCellRenderer renderer = new DefaultTableCellRenderer() {
            JTextArea textArea = new JTextArea();

            @Override
            public Component getTableCellRendererComponent(JTable table, Object value,
                    boolean isSelected, boolean hasFocus, int row, int column) {
                textArea.setText(String.valueOf(value));
                textArea.setLineWrap(true);
                textArea.setWrapStyleWord(true);
                // Divide el texto en líneas si es muy largo
                textArea.setSize(tablaFiltro.getColumnModel().getColumn(column).getWidth(), Short.MAX_VALUE);
                return textArea;
            }
        };

        tablaFiltro.getColumnModel().getColumn(0).setCellRenderer(renderer);
        ajustarAlturaFilas();

    }
    
    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void botonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarActionPerformed
        //actualizarTablaDatos();
        //configurarTabla();

    }//GEN-LAST:event_botonBuscarActionPerformed

    private void tablaFiltroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaFiltroMouseClicked
       /* int columnaBotonIngresar = 2; // La columna del botón "Eliminar" en tu modelo de tabla


        if (tablaFiltro.columnAtPoint(evt.getPoint()) == columnaBotonIngresar) {
            int fila = tablaFiltro.rowAtPoint(evt.getPoint());
            if (fila != -1) {
                String nombreProyecto = (String) tablaFiltro.getValueAt(fila, 0);
                ventanaalaquese dirigue newframe = new ventanaalaquese(nombrePregunta);
                newframe.setVisible(true);
                this.dispose();
            }
        }*/


    }//GEN-LAST:event_tablaFiltroMouseClicked

    private void botonExamenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonExamenActionPerformed
    System.out.println("Boton Examen Clicked");

    // Traverse the hierarchy to find the instance of Principal_Estudiante
    Container parent = getParent();
    while (parent != null && !(parent instanceof Principal_Estudiante)) {
        parent = parent.getParent();
    }

    if (parent instanceof Principal_Estudiante) {
            Principal_Estudiante principalEstudiante = (Principal_Estudiante) parent;
            principalEstudiante.cambiarPanelAFiltroCuestionario();
        } /*else {
            System.out.println("Principal_Estudiante not found in the hierarchy");
        } */





    }//GEN-LAST:event_botonExamenActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonBuscar;
    private javax.swing.JButton botonExamen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTable tablaFiltro;
    // End of variables declaration//GEN-END:variables
}


class TextAreaRenderer extends JTextArea implements TableCellRenderer {

    public TextAreaRenderer() {
        setLineWrap(true);
        setWrapStyleWord(true);
    }

    @Override
    public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
        setText(value != null ? value.toString() : "");
        return this;
    }
}