/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package interfaz;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.GridLayout;
import java.util.ArrayList;
import javax.swing.AbstractButton;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.ButtonGroup;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.SwingConstants;
import Proyecto.Pregunta;

/**
 *
 * @author PC
 */
public class FiltroCuestionario extends javax.swing.JPanel {
    private ExamenGUI examen;
    private Pregunta[] preguntas;

    /**
     * Creates new form FiltroCuestionario
     */
    public FiltroCuestionario() {
        initComponents();
        ExamenGUI examenGUI = new ExamenGUI();
        preguntas = examenGUI.getPreguntas();
        mostrarPreguntasEnPanel(preguntas);

        // Mostrar texto general en el panelTexto
        JTextArea textArea = new JTextArea();
        textArea.setText(examenGUI.getTextoGeneral());
        textArea.setEditable(false); // Hacer el JTextArea no editable
        textArea.setLineWrap(true); // Activar el salto de línea automático
        textArea.setWrapStyleWord(true); // Romper líneas entre palabras
        JScrollPane textAreaScrollPane = new JScrollPane(textArea);

        // Ajustar tamaño del JTextArea
        textArea.setPreferredSize(new Dimension(564, 129));

        panelTexto.setLayout(new BorderLayout());
        panelTexto.add(textAreaScrollPane, BorderLayout.CENTER);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        panelTexto = new javax.swing.JPanel();
        panelPreguntas = new javax.swing.JPanel();
        botonEnviar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        etiquetaTexto = new javax.swing.JLabel();

        jCheckBox1.setText("jCheckBox1");

        setBackground(new java.awt.Color(241, 144, 144));

        jPanel1.setBackground(new java.awt.Color(239, 201, 201));

        panelTexto.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panelTextoLayout = new javax.swing.GroupLayout(panelTexto);
        panelTexto.setLayout(panelTextoLayout);
        panelTextoLayout.setHorizontalGroup(
            panelTextoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelTextoLayout.setVerticalGroup(
            panelTextoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 129, Short.MAX_VALUE)
        );

        panelPreguntas.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panelPreguntasLayout = new javax.swing.GroupLayout(panelPreguntas);
        panelPreguntas.setLayout(panelPreguntasLayout);
        panelPreguntasLayout.setHorizontalGroup(
            panelPreguntasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelPreguntasLayout.setVerticalGroup(
            panelPreguntasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 165, Short.MAX_VALUE)
        );

        botonEnviar.setText("Enviar");
        botonEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEnviarActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(255, 102, 102));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Preguntas");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(236, 236, 236)
                .addComponent(jLabel1)
                .addContainerGap(242, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(255, 102, 102));

        etiquetaTexto.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        etiquetaTexto.setText("Texto");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(248, 248, 248)
                .addComponent(etiquetaTexto)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(etiquetaTexto)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonEnviar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(panelTexto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelPreguntas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(26, 26, 26))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(panelTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(panelPreguntas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonEnviar)
                .addGap(31, 31, 31))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    private void mostrarPreguntasEnPanel(Pregunta[] preguntas) {
        JScrollPane scrollPane = new JScrollPane();
        scrollPane.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
        scrollPane.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_ALWAYS);

        // Asegúrate de que el rango de velocidad de desplazamiento vertical no sea nulo
        scrollPane.getVerticalScrollBar().setUnitIncrement(16);

        JPanel panelPreguntasWrapper = new JPanel();
        panelPreguntasWrapper.setBackground(Color.white);
        panelPreguntasWrapper.setLayout(new BoxLayout(panelPreguntasWrapper, BoxLayout.Y_AXIS));

        int totalHeight = 0;

        for (Pregunta pregunta : preguntas) {
            JPanel preguntaPanel = new JPanel();
            preguntaPanel.setBackground(Color.white);
            preguntaPanel.setLayout(new BoxLayout(preguntaPanel, BoxLayout.Y_AXIS));

            JLabel preguntaLabel = new JLabel(pregunta.getEnunciado());
            preguntaPanel.add(preguntaLabel);

            ButtonGroup buttonGroup = new ButtonGroup();

            for (String alternativa : pregunta.getAlternativas()) {
                JRadioButton radioButton = new JRadioButton(alternativa);
                preguntaPanel.add(radioButton);
                buttonGroup.add(radioButton);
            }

            panelPreguntasWrapper.add(preguntaPanel);
            // Usar setPreferredSize en lugar de setMaximumSize para las áreas rígidas
            panelPreguntasWrapper.add(Box.createRigidArea(new Dimension(0, 10)));

            // Sumar la altura de cada pregunta y espacio entre preguntas
            totalHeight += preguntaPanel.getPreferredSize().height + 10;
        }

        // Configurar el tamaño preferido del panel de preguntas para evitar que se agrande automáticamente
        Dimension preferredSize = new Dimension(515, totalHeight);
        panelPreguntasWrapper.setPreferredSize(preferredSize);
        panelPreguntasWrapper.setMaximumSize(preferredSize);

        // Configurar el tamaño preferido del scrollPane
        scrollPane.setViewportView(panelPreguntasWrapper);
        scrollPane.setPreferredSize(new Dimension(515, Math.min(165, totalHeight))); // Limitar a 165 de alto

        panelPreguntas.removeAll();
        panelPreguntas.setLayout(new BorderLayout());
        panelPreguntas.add(scrollPane, BorderLayout.CENTER);

        panelPreguntas.revalidate();
        panelPreguntas.repaint();
    }




    private void botonEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEnviarActionPerformed
        JPanel panelRespuestas = new JPanel();
        panelRespuestas.setBackground(Color.white);
        panelRespuestas.setLayout(new BoxLayout(panelRespuestas, BoxLayout.Y_AXIS));

        for (Pregunta pregunta : preguntas) {
            JPanel respuestaPanel = new JPanel();
            respuestaPanel.setBackground(Color.white);
            respuestaPanel.setLayout(new BoxLayout(respuestaPanel, BoxLayout.Y_AXIS));

            JLabel preguntaLabel = new JLabel(pregunta.getEnunciado());
            respuestaPanel.add(preguntaLabel);

            ButtonGroup buttonGroup = new ButtonGroup();

            for (String alternativa : pregunta.getAlternativas()) {
                JRadioButton radioButton = new JRadioButton(alternativa);
                radioButton.setEnabled(false); // Deshabilitar los botones para que no se puedan cambiar después de enviar
                respuestaPanel.add(radioButton);
                buttonGroup.add(radioButton);

                // Marcar la respuesta correcta y las incorrectas
                if (alternativa.equals(pregunta.getRespuestaCorrecta())) {
                    if (radioButton.isSelected()) {
                        radioButton.setForeground(Color.GREEN);
                    }
                    radioButton.setSelected(true);
                } else if (radioButton.isSelected()) {
                    radioButton.setForeground(Color.RED);
                }
            }

            // Mostrar la respuesta correcta y el razonamiento
            JLabel respuestaCorrectaLabel = new JLabel("Respuesta correcta: " + pregunta.getRespuestaCorrecta());
            JLabel razonamientoLabel = new JLabel("Razonamiento: " + pregunta.getRazonamiento());

            respuestaPanel.add(respuestaCorrectaLabel);
            respuestaPanel.add(razonamientoLabel);

            panelRespuestas.add(respuestaPanel);
            panelRespuestas.add(Box.createRigidArea(new Dimension(0, 10)));
        }

        // Configurar el tamaño preferido del panel de respuestas
        JScrollPane scrollPane = new JScrollPane(panelRespuestas);
        scrollPane.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
        scrollPane.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_ALWAYS);
        scrollPane.getVerticalScrollBar().setUnitIncrement(16);
        scrollPane.setPreferredSize(new Dimension(515, Math.min(165, panelRespuestas.getPreferredSize().height)));

        // Reemplazar el panel de preguntas con el panel de respuestas
        panelPreguntas.removeAll();
        panelPreguntas.setLayout(new BorderLayout());
        panelPreguntas.add(scrollPane, BorderLayout.CENTER);

        panelPreguntas.revalidate();
        panelPreguntas.repaint();



    }//GEN-LAST:event_botonEnviarActionPerformed
 


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonEnviar;
    private javax.swing.JLabel etiquetaTexto;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel panelPreguntas;
    private javax.swing.JPanel panelTexto;
    // End of variables declaration//GEN-END:variables
}
